### PR TITLE
Adds missing keys to svg feature

### PR DESCRIPTION
**Pull request by vwallen**

### CODE REVIEW

**Review by Elchi3 — APPROVED** [review]
Looks good to me. Minor: move it to line 607?

**Comment by vwallen** [comment]
> Looks good to me. Minor: move it to line 607?

So I better understand, why is that better than grouping these with the property?

**Comment by vwallen** [comment]
Ugh, you're right and that was my intent, but I missed it

**Review by Elchi3 — APPROVED** [review]
No worries and thank you! :)

**Pull request merged**
