### PR TITLE
Add the `<data>` element

### PR DESCRIPTION
**Pull request by petele**
There's a discrepancy between the versions for `api.HTMLDataElement` and `html.elements.data` that probably needs to be fixed in the BCD

### CODE REVIEW

**Comment by foolip** [comment]
The Edge version will be ≤18 after https://github.com/web-platform-dx/web-features/pull/1398 and indeed we need to fix this in BCD. Just trusting the API data is probably OK for something this new, and given that the element has an attribute. (For elements without any attributes, not giving them their own interface has very little impact, and has probably happened much more often.)

**Comment by foolip** [comment]
I've sent https://github.com/mdn/browser-compat-data/pull/23830. If you'd like to use `compute_from` to get the right versions with a TODO pointing to https://github.com/mdn/browser-compat-data/pull/23830, that's OK.

**Comment by petele** [comment]
> I've sent [mdn/browser-compat-data#23830](https://github.com/mdn/browser-compat-data/pull/23830). If you'd like to use `compute_from` to get the right versions with a TODO pointing to [mdn/browser-compat-data#23830](https://github.com/mdn/browser-compat-data/pull/23830), that's OK.

I'm OK to leave it here and wait for that to land.

**Comment by petele** [comment]
@foolip & @ddbeck - the test is failing on this one because of an invalid date, looking at the `dist` file, I see an odd date...

`baseline_low_date: ≤2018-10-02`

**Comment by foolip** [comment]
@petele ranges in versions and dates are a result of https://github.com/web-platform-dx/web-features/pull/1398. Can you rebase and then run `npm run dist` again to get it all in order?

**Comment by petele** [comment]
@foolip - done.

**Review by foolip — APPROVED** [review]

**Pull request merged**
