### PR TITLE
Add Brian and Patrick as peers

### PR DESCRIPTION
**Pull request by foolip**

### CODE REVIEW

**Comment by foolip** [comment]
This needs to be approved by current owners. Adding them as reviewers.

**Review by Elchi3 — APPROVED** [review]

**Review by atopal — APPROVED** [review]
LGTM!

**Review by ddbeck — APPROVED** [review]

**Review by jgraham — APPROVED** [review]

**Review by LeoMcA — APPROVED** [review]

**Comment by foolip** [comment]
That's a lot of green checkmarks, so I'm going to merge this now.

**Comment by foolip** [comment]
@dontcallmedom can you arrange for @bkardell to have write access?

**Comment by dontcallmedom** [comment]
done

**Comment by bkardell** [comment]
Hey that's me, I'm a peer!

**Pull request merged**
