### PR TITLE
Add stable-array-sort.dist.yml

### PR DESCRIPTION
**Pull request by foolip**

### CODE REVIEW

**Review by Elchi3 — COMMENTED** [review]
Should this be part of the `arrays` group?

**Comment by foolip** [comment]
> Should this be part of the `arrays` group?

Yes, certainly: https://github.com/web-platform-dx/web-features/pull/1147

**Comment by Elchi3** [comment]
Merged. I assume this dist file needs to be regenerated prior to merging this PR.

**Comment by foolip** [comment]
@Elchi3 indeed, now updated

**Review by Elchi3 — APPROVED** [review]

**Pull request merged**
