### PR TITLE
Mark AVIF as Baseline low

### PR DESCRIPTION
**Pull request by foolip**
Opening this after seeing @captainbrosset post https://mas.to/@patrickbrosset/111606297691549413.

Leaving this as draft until Edge 121 is released. The versions for the other browsers also need to be confirmed.

### CODE REVIEW

**Comment by captainbrosset** [comment]
Related: MDN docs for AVIF being supported in Edge 121 have been added: https://github.com/mdn/content/pull/31145.
CanIUse PR also up: https://github.com/Fyrd/caniuse/pull/6924

**Comment by foolip** [comment]
Updated with the final release date from https://github.com/mdn/browser-compat-data/blob/4ffe27981b17180c2386bdb05f9b4a43e2573879/browsers/edge.json#L347-L352

**Comment by foolip** [comment]
@captainbrosset can you review/merge?

**Review by captainbrosset — APPROVED** [review]
Sorry about the delay. I missed this one.

**Pull request merged**
