### PR TITLE
Adds ruby annotation layout properties and group

### PR DESCRIPTION
**Pull request by vwallen**

### CODE REVIEW

**Review by jamesnw — APPROVED** [review]
LGTM!

**Review by autonome — CHANGES_REQUESTED** [review]
Can you remove these keys from `features/draft/spec/css-ruby-1.yml`? Hmm, unless y'all haven't been doing that for CSS keys?

**Comment by jamesnw** [comment]
> Can you remove these keys from `features/draft/spec/css-ruby-1.yml`? Hmm, unless y'all haven't been doing that for CSS keys?

We haven't been removing them- for some reason I thought we were avoiding that to avoid merge conflicts. I'm fine either way?

**Review by autonome — APPROVED** [review]

**Comment by autonome** [comment]
> > Can you remove these keys from `features/draft/spec/css-ruby-1.yml`? Hmm, unless y'all haven't been doing that for CSS keys?
> 
> We haven't been removing them- for some reason I thought we were avoiding that to avoid merge conflicts. I'm fine either way?

Never mind in that case! I have been, likely because early on was told to do so. But since nothing actually tests the aggregate set of keys in the drafts folders against the completed keys, it doesn't really matter. Worst that happens is someone picks out keys in drafts to work on, and they've already been done. But I typically check keys first before starting work on anything, regardless.

**Pull request merged**
