### PR TITLE
Pin status of async clipboard to navigator.clipboard

### PR DESCRIPTION
**Pull request by foolip**

### CODE REVIEW

**Comment by foolip** [comment]
This leaves `navigator.clipboard.read()` and `readText()` as not Baseline, and that needs fixing in BCD.

**Review by ddbeck — APPROVED** [review]

**Comment by ddbeck** [comment]
Should this actually fix https://github.com/web-platform-dx/web-features/issues/1249? There's still some question about the data quality, I think.

**Comment by foolip** [comment]
No, it doesn't fully fix https://github.com/web-platform-dx/web-features/issues/1249, I'll unlink it.

**Comment by foolip** [comment]
Holding off merging. https://caniuse.com/async-clipboard treats Firefox and Safari iOS as having partial support, and the Chrome versions aren't the same.

**Comment by foolip** [comment]
https://github.com/web-platform-dx/web-features/pull/1346 results in some changes here...

**Comment by foolip** [comment]
Let's go with https://github.com/web-platform-dx/web-features/pull/1349 instead.

**Pull request closed without merging**
