### PR TITLE
`picture-in-picture`: add compat features

### PR DESCRIPTION
**Pull request by ddbeck**
Some ideas for reviewing this:

- Are listed features plausible pieces of the feature as a whole?
- Are any of the listed features later additions, part of a distinct sub feature, or otherwise excludable?
- Are any pieces missing?

### CODE REVIEW

**Comment by Elchi3** [comment]
https://github.com/mdn/browser-compat-data/pull/20531 added new Picture in Picture features. Would that be a new group? If so, would there be an umbrella group that combines all PiP features?

**Comment by ddbeck** [comment]
> Would that be a new group? If so, would there be an umbrella group that combines all PiP features?

Yes and yes. Yes, I imagine we'll eventually need a omni-picture-in-picture group that contains two groups inside it:

- `picture-in-picture` (the feature shown in this PR)
- `document-picture-in-picture` or something like it (covering the features indicated in https://github.com/mdn/browser-compat-data/pull/20531)

I'd expect that the first feature (which applies to `<video>` elements only) to be distinct from the generalized document feature, in part because they've come about separately.

We don't yet have the machinery in this repo to represent groups-of-groups (in part because we only have one good example at the moment, for `grid` and `subgrid`).

**Comment by Elchi3** [comment]
Thanks Daniel! Some thoughts, which are maybe nitpicky but I think it helps us to think about groups some more.

I was wondering if there is PiP "infrastructure" that future specs like the new document-picture-in-picture spec would rely on, but apparently that isn't the case? At least I couldn't find information if both use the same permission policy, for example.

If that would be the case, though, I would have proposed three groups:
 - picture-in-picture (for PiP "infra" things like the PiP permission policy etc)
 - video-picture-in-picture (most of the features in this PR)
 - document-picture-in-picture (features from the new spec).

But probably the two specs can be implemented independently and do not share "infrastructure" features. So, the two groups you propose make sense to me in that case.

The only thing I wonder then is what the ID of the omni-picture-in-picture group would be if this PR uses "picture-in-picture" for "video-picture-in-picture" already.

**Comment by ddbeck** [comment]
Thanks for your patience while I came back around to this, @Elchi3.

> I would have proposed three groups:
> 
> * picture-in-picture (for PiP "infra" things like the PiP permission policy etc)
> * video-picture-in-picture (most of the features in this PR)
> * document-picture-in-picture (features from the new spec).

I see why you'd create three groups, but I've got some questions about this approach:

- Does this not flip the structure a bit? `video-picture-in-picture` and `document-picture-in-picture` would depend on `picture-in-picture`. This suggests that `picture-in-picture` is the most limited and specific feature—one you can't even use by itself.
- Would we expect web developers to _ever_ recognize `picture-in-picture` as a distinct feature, from `video-picture-in-picture` and `document-picture-in-picture`?

My suspicion here is that `video-picture-in-picture` and `document-picture-in-picture` have overlapping internals (e.g., a permission policy, though the spec for document picture-in-picture doesn't speak to this at all).

**Comment by ddbeck** [comment]
Coming back to this now, there's a good distinction noted in https://github.com/web-platform-dx/web-features/issues/217: we need to be able to talk about features as being related _or_ dependent. Right now, I think `picture-in-picture` (as defined here) and `document-picture-in-picture` are related (perhaps `picture-in-picture-technologies`) but not dependent on each other (they're separate APIs).

Has your thinking on this changed at all, @Elchi3?

**Comment by Elchi3** [comment]
> Right now, I think `picture-in-picture` (as defined here) and `document-picture-in-picture` are related (perhaps `picture-in-picture-technologies`) but not dependent on each other (they're separate APIs).

Yes, makes sense to me.

(I don't know if `picture-in-picture` for video PiP is too generic given there are two PiP APIs, but maybe I'm overthinking it.)

**Review by foolip — APPROVED** [review]
This feature list makes sense to me. It doesn't include https://wicg.github.io/document-picture-in-picture/#api, and shouldn't.

**Pull request merged**
