### PR TITLE
Remove chromestatus.com usage stats

### PR DESCRIPTION
**Pull request by foolip**
Chrome usage stats for web-features is now being maintained in the
Chromium repository:
https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/public/mojom/use_counter/metrics/webdx_feature.mojom;drc=41e539e573351d8e57160f2de3201c28e4a3cc19

All of the 87 features touched here have an enum entry in the above
webdx_feature.mojom file, confirmed by transforming the feature
identifier to kCamelCase and looking for an exact match in the list.

### CODE REVIEW

**Comment by foolip** [comment]
This is draft because it depends on https://github.com/web-platform-dx/web-features/pull/1234.

**Comment by foolip** [comment]
@jstenback FYI, removing this from web-features as discussed. It realized I could transform the identifiers quickly in VS Code, so I just did the check again the enum directly, and found one outlier, the draft speech recognition feature.

**Comment by foolip** [comment]
> So should we keep the `usage_stats` field at all?

I wanted to play it safe and remove it later if it's been unused for some time, because removing it and adding back would be churn. But I can remove it if you think it'll turn into unused cruft, which honestly is likely.

**Comment by jstenback** [comment]
I went ahead and created a CL to add the speech recognition one to Chromium but realized in that process that it's already there. So AFAICT this is all good to go.

**Review by ddbeck — APPROVED** [review]
> > So should we keep the `usage_stats` field at all?
> 
> I wanted to play it safe and remove it later if it's been unused for some time, because removing it and adding back would be churn. But I can remove it if you think it'll turn into unused cruft, which honestly is likely.

@foolip I'm happy either way. If you choose to merge this without removing the field, please file an issue so we get to it later.

**Comment by foolip** [comment]
> > > So should we keep the `usage_stats` field at all?
> > 
> > 
> > I wanted to play it safe and remove it later if it's been unused for some time, because removing it and adding back would be churn. But I can remove it if you think it'll turn into unused cruft, which honestly is likely.
> 
> @foolip I'm happy either way. If you choose to merge this without removing the field, please file an issue so we get to it later.

I'll just remove it entirely now.

**Pull request merged**
