### PR TITLE
Add `const` and `let` features

### PR DESCRIPTION
**Pull request by ddbeck**
At some point, I'll be making an ES6 group, so these will eventually join that group. Otherwise, these would feel pretty trivial.

These correspond to:

- https://caniuse.com/const
- https://caniuse.com/let

---

This is a new feature. Here are some ideas for reviewing it:

- Is this a recognizable web feature to web developers? (caniuse features are often made by request, so it's likely, but let's double check our work here.)
- Is this a reasonable identifier for the feature?
- Does this have a reasonable spec link?
- Does this have a reasonable caniuse reference?
- Are the [mdn/browser-compat-data](https://github.com/mdn/browser-compat-data) features plausible pieces of the feature as a whole?
- Are any pieces missing?
- Are any of the listed features later additions, part of a distinct sub feature, or otherwise excludable?

### CODE REVIEW

**Comment by Elchi3** [comment]
Is there any prior discussion about feature group definitions that include just a single feature? Do we generally think groups with just one feature are useful?

Would you create a group for the JavaScript `var` statement? Probably not I guess? Is the justification that these two features would be part of another (ES6) group? Why not just have them in that group then?

**Comment by foolip** [comment]
At least for parts of JavaScript that are old by now, I think we should have groups like "es5", "es6", etc., and put these into "es6". I think we can lump everything pre-ES6 into ES5, and we also need to decide if/when we switch from version numbers to years. https://en.wikipedia.org/wiki/ECMAScript_version_history is a good starting point to understand the evolution.

**Comment by foolip** [comment]
I've filed https://github.com/web-platform-dx/web-features/issues/558 to track that idea.

**Comment by ddbeck** [comment]
I'm going to withdraw this for now. Snapshots seems to be the direction of an answer for some of this, so let's come back to this later.

**Pull request closed without merging**
