### PR TITLE
Clean-up drafts of WebGL1 vs WebGL2

### PR DESCRIPTION
**Pull request by petele**

### CODE REVIEW

**Comment by petele** [comment]
@foolip or @ddbeck - can I just get a super quick LGTM on this. It only affects the `drafts` of the WebGL & WebGL2 files. It'll make creating the actual WebGL stuff easier.

**Review by foolip — APPROVED** [review]

**Comment by foolip** [comment]
@petele merged! Just note that we'll update these drafts weekly (@tropicadri is working on that) so any manual changes risk being reverted unless other PRs land that use the BCD keys.

**Comment by petele** [comment]
> @petele merged! Just note that we'll update these drafts weekly (@tropicadri is working on that) so any manual changes risk being reverted unless other PRs land that use the BCD keys.

Got it - thanks. I'll work on it tomorrow, so hopefully I won't run into that issue.

**Comment by tropicadri** [comment]
#1502 has the workflow for updating weekly, waiting for review.

**Pull request merged**
