### PR TITLE
Give the draft updater workflow pull requests write permission

### PR DESCRIPTION
**Pull request by foolip**

### CODE REVIEW

**Comment by foolip** [comment]
@tropicadri I haven't tried this, but maybe it will work :)

**Comment by tropicadri** [comment]
I am not  100% sure it will, work, but let's give it a try!

**Review by tropicadri — APPROVED** [review]

**Comment by foolip** [comment]
Unfortunately, it didn't work:
https://github.com/web-platform-dx/web-features/actions/runs/10168469504/job/28123129636#step:7:81

@dontcallmedom @tidoust can either of you help change the org settings following @tropicadri's instructions in https://github.com/web-platform-dx/web-features/pull/1502#issuecomment-2253502610?

**Comment by tidoust** [comment]
> @dontcallmedom @tidoust can either of you help change the org settings following @tropicadri's instructions in [#1502 (comment)](https://github.com/web-platform-dx/web-features/pull/1502#issuecomment-2253502610)?

Sure! I just checked the "Allow GitHub Actions to create and approve pull requests" checkbox at the organization level. Other settings look good to me.

**Comment by foolip** [comment]
Thank you @tidoust! It still doesn't work, but it's because of something else now that I'll debug.

**Pull request merged**
