### PR TITLE
Adding missing descriptions and making them mandatory/published

### LINKED ISSUE #736: Publish descriptions
In review we have started adding descriptions to new features as a matter of course. Let's add the missing ones and then add this to the schema and published data.

### PR DESCRIPTION
**Pull request by captainbrosset**
This PR describes all the features that don't yet have a description field. Fixes  #736.
This PR also makes the description field mandatory so that, going forward, we have to have descriptions.

Reviewers: most of this is taken from MDN, Can I Use, specs, and Wikipedia. My goal was to cover 100% of files, not to be 100% correct on all of them. I believe that once we have the descriptions in place, at least, we can't introduce new features without descriptions, but we can always improve the existing ones.

### CODE REVIEW

**Comment by captainbrosset** [comment]
Update: I'm taking a break from this. Here is the list of remaining web features:

* fetch-priority
* font-optical-sizing
* font-synthesis
* font-variant-alternates
* fonts
* html-media-capture
* http11
* http2
* http3
* idle-detection
* image-set
* import-maps
* indeterminate
* intersection-observer
* media-query-range-syntax
* modulepreload
* offscreen-canvas
* picture-in-picture
* registered-custom-properties
* scheduler
* server-timing
* set-methods
* shadow-dom
* slot
* speech-recognition
* speech-synthesis
* starting-style
* sticky-positioning
* storage-buckets
* structured-clone
* subgrid
* svg2-script-html-equivalence

**Comment by captainbrosset** [comment]
Resuming work on this. Remaining features:

image-set
import-maps
indeterminate
intersection-observer
media-query-range-syntax
modulepreload
offscreen-canvas
picture-in-picture
registered-custom-properties
scheduler
server-timing
set-methods
shadow-dom
slot
speech-recognition
speech-synthesis
starting-style
sticky-positioning
storage-buckets
structured-clone
subgrid
svg2-script-html-equivalence

**Comment by foolip** [comment]
@captainbrosset I see that you resolved conflicts, but by replacing the original descriptions. Unless you think they're bad, can you back those changes out to focus only on missing descriptions?

**Comment by foolip** [comment]
Thinking about how to get this done with maximum velocity, I think having a single big PR is going to lead to a lot of good descriptions being held back by discussions on a few tricky cases. I would suggest splitting this into many small PRs, perhaps not one per descriptions, but at most 10 per PR so that review comments are manageable on each. Other than alphabetically, I think the easiest split would be by spec, and would do some amount of useful clustering.

**Comment by captainbrosset** [comment]
Closing this PR and opening multiple smaller PRs instead.

**Comment by captainbrosset** [comment]
This has now been replaced by https://github.com/web-platform-dx/web-features/pull/750, https://github.com/web-platform-dx/web-features/pull/751, https://github.com/web-platform-dx/web-features/pull/752, https://github.com/web-platform-dx/web-features/pull/753, https://github.com/web-platform-dx/web-features/pull/754, https://github.com/web-platform-dx/web-features/pull/755, https://github.com/web-platform-dx/web-features/pull/756, https://github.com/web-platform-dx/web-features/pull/757, https://github.com/web-platform-dx/web-features/pull/758, https://github.com/web-platform-dx/web-features/pull/759, https://github.com/web-platform-dx/web-features/pull/760,  https://github.com/web-platform-dx/web-features/pull/761.

**Pull request closed without merging**
