### PR TITLE
Release web-features 1.0.0

### PR DESCRIPTION
**Pull request by foolip**
Hoorah.

Closes https://github.com/web-platform-dx/web-features/issues/735.

### CODE REVIEW

**Comment by foolip** [comment]
https://github.com/web-platform-dx/web-features/pull/1398 should also be merged before 1.0.0, of course.

**Comment by captainbrosset** [comment]
Definitely not against going to 1.0.0 if that helps us communicate breaking changes more easily.
Unlike more traditional libraries, though, which you can still keep on using for a while if you don't have time to update your code to adapt to the breaking change, you can't really keep using web-features 1.0.0 if 2.0.0 is out. Otherwise you risk displaying outdated browser version and baseline information.
I'm not saying we shouldn't do it. Let's do all, by all means, but maybe have something in the README that tells consumers how each version comes with updated dates/versions/baseline statuses, and that it's a best practice (or really, the only practice) to keep updating their dependency.

**Comment by captainbrosset** [comment]
What about #1450? It's a schema change. Should we wait for that to land before going to 1.0.0?

**Comment by foolip** [comment]
@captainbrosset, yes, that too! I sent it now because it's a breaking change, sorry I didn't link them together.

**Comment by ddbeck** [comment]
> Let's do all, by all means, but maybe have something in the README that tells consumers how each version comes with updated dates/versions/baseline statuses, and that it's a best practice (or really, the only practice) to keep updating their dependency.

Yes, let's do this. Also, we can mark the previous releases on npm as deprecated. It might even be a good idea to do that on a rolling basis (e.g., if you're using a version of web-features more than a month old, you start getting the deprecation warning from npm).

**Comment by foolip** [comment]
https://github.com/web-platform-dx/web-features/pull/1398 and https://github.com/web-platform-dx/web-features/pull/1450 have been merged now.

One more thing we can do while we're add it is include the schema in the release. I'll do that now.

**Comment by foolip** [comment]
https://github.com/web-platform-dx/web-features/pull/1348 is also done now.

**Review by ddbeck — APPROVED** [review]

**Pull request merged**
